# Dockerfile References: https://docs.docker.com/engine/reference/builder/

# Start from specific golang base image
FROM golang:1.13.7-alpine3.11
RUN apk update && apk add git
RUN apk --no-cache add ca-certificates
RUN apk add --no-cache bash

WORKDIR /workspace

RUN git clone https://github.com/go-swagger/go-swagger --branch v0.21.0

WORKDIR go-swagger

RUN go install ./cmd/swagger

WORKDIR /workspace
