# This is a dockerfile to build a docker in docker (dind) image with the user who is building 
#
# ubunut 18.04.2 with kernel version 4.18.0-16
FROM ubuntu:bionic-20190307
RUN apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install -y make gcc python2.7 libelf-dev \
	python-yaml python-jinja2

RUN apt-get clean
