# ubunut 20.04
FROM ubuntu:focal-20200606
RUN apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install -y python3 python2 curl libpixman-1-0 \
	libfdt-dev libglib2.0-dev ssh gcovr cpu-checker libnl-3-200 libnl-route-3-200 time
ENV ASAN_OPTIONS disable_coredump=0:unmap_shadow_on_exit=1:abort_on_error=1
