# ubunut 18.04.2 with kernel version 4.18.0-16
FROM docker.fungible.com/run_funos:latest
RUN apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install -y iproute2 redis-server python-pip

RUN pip install flask redis thrift
