# Start from specific golang base image
FROM golang:1.16.5-alpine

RUN set -ex; \
    apk add --no-cache --virtual .buildpack-deps \
    git \
    make \
    build-base \
    docker \
    docker-compose \
    net-tools \
    jq \
    curl \
    kafkacat \
    && rm -rf /var/cache/apk/*

WORKDIR /workspace
