# Start from specific golang base image
FROM golang:1.16.5-alpine

RUN set -ex; \
    apk add --no-cache --virtual .buildpack-deps \
    git \
    make \
    build-base \
    docker \
    docker-compose \
    net-tools \
    jq \
    curl \
    kafkacat \
    openjdk11 \
    bash \
    && rm -rf /var/cache/apk/*

WORKDIR /workspace

RUN curl http://dochub.fungible.local/doc/sw/fc-deploy/deployment/helm-3.2.2/helm -o /usr/local/bin/helm && chmod +x /usr/local/bin/helm
